USE [Samsung_Dev]
GO

/****** Object:  StoredProcedure [dbo].[AC_PRODUCT_INIT]    Script Date: 2017-01-25 4:53:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Diana Azbel
-- Create date: 2017-01-25
-- Description:	AC_PRODUCT table first load
-- =============================================
CREATE PROCEDURE [dbo].[AC_PRODUCT_INIT] 
AS
BEGIN
 	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	
	DECLARE @currentDate datetime;
	SET @currentDate = GETDATE();
	SET NOCOUNT ON;

	IF exists(SELECT TOP (1) * FROM  [dbo].[AC_PRODUCT])
	BEGIN
	  ;THROW   51000, 'This is not first load. Make sure AC_Product is empty.', 1;   
	END
	
 	INSERT INTO  [dbo].[AC_Product] (PRODUCT_ID,PRODUCT_NAME,SKU_ID,MODEL_NUMBER,PRODUCT_DESCRIPTION
					,SOURCE_COUNTRY,SRP,PRICE_DESC,PROMO_PRICE,PRODUCT_URL
					,DETAIL_URL,IMAGE_URL,PROD_URL_VALID,PROD_URL_TESTED,ACCESSORY_FLAG
					,FAMILY_NAME,SUPPORT_ONLY,FRIENDLY_NAME,SAVING_AMOUNT,PERCENT_OFF
					,ECOMMERCEFLAG,EOL_FLG,SRC_SYS_PRODUCT_ID,MERKLE_CATEGORY_NAME
					,PRODUCT_DIVISION_NAME,PRODUCT_GROUP_NAME,PRODUCT_CATEGORY_NAME,PRODUCT_SUBCATEGORY_NAME
					,DATAMART_ACCOUNT_DATE)
	SELECT P.PRODUCT_ID,P.PRODUCT_NAME,P.SKU_ID,P.MODEL_NUMBER,P.PRODUCT_DESCRIPTION
					,P.SOURCE_COUNTRY,P.SRP,P.PRICE_DESC,P.PROMO_PRICE,P.PRODUCT_URL
					,P.DETAIL_URL,P.IMAGE_URL,P.PROD_URL_VALID,P.PROD_URL_TESTED,P.ACCESSORY_FLAG
					,P.FAMILY_NAME,P.SUPPORT_ONLY,P.FRIENDLY_NAME,P.SAVING_AMOUNT,PERCENT_OFF
					,P.ECOMMERCEFLAG,P.EOL_FLG,P.SRC_SYS_PRODUCT_ID,V_P.MERKLE_CATEGORY_NAME
					,V_P.PRODUCT_DIVISION_NAME,V_P.PRODUCT_GROUP_NAME,V_P.PRODUCT_CATEGORY_NAME,V_P.PRODUCT_SUBCATEGORY_NAME 
					,@currentDate
	FROM [DBO].[PRODUCT] P
    LEFT JOIN [dbo].[V_PRODUCT_HIERARCHY] V_P ON V_P.PRODUCT_ID = P.PRODUCT_ID
END

GO

