USE [Samsung_Dev]
GO

/****** Object:  StoredProcedure [dbo].[AC_PRODUCT_PIVOT_INIT]    Script Date: 2017-01-25 4:54:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Diana Azbel (TDI)
-- Create date: 2017-01-25
-- Description:	AC_PRODUCT_PIVOT Table First load
-- =============================================
CREATE PROCEDURE [dbo].[AC_PRODUCT_PIVOT_INIT] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF exists(SELECT TOP (1) * FROM  [dbo].[AC_PRODUCT_PIVOT])
	BEGIN
	  ;THROW   51000, 'This is not first load. Make sure AC_ProductPivot is empty.', 1;   
	END

	
	INSERT INTO  [dbo].[AC_PRODUCT_PIVOT] (REGISTRATION_ID,EMAIL_ADDRESS_ID,EMAIL_ADDRESS,SRC_SYS_CUSTOMER_ID
											,SRC_SYS_REGISTRATION_ID,SEQUENCE_NUM,REGISTRATION_DATE,PRODUCT_ID
											,SOURCE_ID,SERIAL_NUMBER_TXT,CARRIER_ID,PURCHASE_STORE_NAME
											,PURCHASE_STORE_COUNTRY,PURCHASE_DATE,PURCHASE_STORE_CITY,PURCHASE_STORE_STATE
											,WARRANTY_IND,COMPANY_CODE,BOGUS_SERIAL_FLAG )
	SELECT P_R.REGISTRATION_ID,P_R.EMAIL_ADDRESS_ID,V_E.EMAIL_ADDRESS,V_E.SRC_SYS_CUSTOMER_ID
											,P_R.SRC_SYS_REGISTRATION_ID,P_R.SEQUENCE_NUM,P_R.REGISTRATION_DATE,P_R.PRODUCT_ID
											,P_R.SOURCE_ID,P_R.SERIAL_NUMBER_TXT,P_R.CARRIER_ID,P_R.PURCHASE_STORE_NAME
											,P_R.PURCHASE_STORE_COUNTRY,P_R.PURCHASE_DATE,P_R.PURCHASE_STORE_CITY,P_R.PURCHASE_STORE_STATE
											,P_R.WARRANTY_IND,P_R.COMPANY_CODE,P_R.BOGUS_SERIAL_FLAG
	FROM [SAM].[PRODUCT_REGISTRATION_UNIQUE] P_R
    JOIN dbo.V_EMAIL_OPTIN_MAILABLE V_E ON V_E.EMAIL_ADDRESS_ID = P_R.EMAIL_ADDRESS_ID
END

GO

