CREATE TABLE AC_Product
(  
Product_ID	int NOT NULL,
Product_Name	varchar(50),
SKU_ID	int,
Model_Number	varchar(20),
Product_Description	varchar(200),
Source_Country	varchar(2),
SRP	decimal(18,2),
Price_Desc	varchar(250),
Promo_Price	decimal(18,2),
product_url	varchar(2000),
detail_url	varchar(500),
image_url	varchar(500),
prod_url_valid	bit,
prod_url_tested	smalldatetime,
Accessory_flag	varchar(1),
family_name	varchar(100),
support_only	varchar(4),
friendly_name	varchar(50),
saving_amount	decimal(18,2),
percent_off	decimal(38,15),
ecommerceFlag	varchar(1),
eol_flg	bit,
Src_Sys_Product_ID	varchar(20),
Merkle_Category_Name	varchar(50),
Product_Division_Name	varchar(50),
Product_Group_Name	varchar(50),
Product_Category_Name	varchar(50),
Product_SubCategory_Name	varchar(50)
)