CREATE TABLE AC_Recipient   
(  
  
Email_Address	varchar(255) NOT NULL,
BP_Number	varchar(20) NOT NULL,
Email_Address_ID	int,
Company_Code	varchar(4),
First_Name	varchar(50),
Last_Name	varchar(50),
Address_Line_1	varchar(80),
Address_Line_2	varchar(80),
City	varchar(50),
State_Code	varchar(3),
Country	varchar(50),
Province	varchar(50),
Zip_Code	varchar(20),
Home_Phone	varchar(32),
Work_Phone	varchar(32),
Cell_Phone	varchar(32),
Samsung_Join_Date	datetime,
Individual_ID	int,
Created_Date	datetime NOT NULL,
deactivation_date	datetime,
Marital_Status_Code	varchar(1),
Gender_Code	varchar(1),
Birth_Date	datetime,
Age_Group	varchar(1),
Residence_Type	varchar(1),
Home_Ownership	varchar(1),
Income_Level	varchar(1),
Samsung_Product_Owner_Code	varchar(20),
Company_Name	varchar(100),
Job_Title	varchar(200),
Language_Type_Code	varchar(1),
B2B_Company_Name	varchar(256),
Lead_Source	varchar(30),
Product_Interest	varchar(30),
Industry	varchar(200),
Source_Name	varchar(50),
Orig_Source	varchar(10) NOT NULL,
Carrier_Name	varchar(50),
Permission_ID	int NOT NULL,
Datamart_Account_Date	datetime NOT NULL

)