SELECT * FROM [SAM].[ACCOUNT]
JOIN [dbo].[V_EMAIL_OPTIN_MAILABLE] ON [SAM].[ACCOUNT].EMAIL_ADDRESS_ID = [dbo].[V_EMAIL_OPTIN_MAILABLE].EMAIL_ADDRESS_ID
JOIN [SAM].[EMAIL_PROFILE_SAMSUNG] ON [SAM].[ACCOUNT].EMAIL_ADDRESS_ID = [SAM].[EMAIL_PROFILE_SAMSUNG].EMAIL_ADDRESS_ID
JOIN [dbo].[EMAIL_PROFILE] ON [SAM].[ACCOUNT].EMAIL_ADDRESS_ID = [dbo].[EMAIL_PROFILE].EMAIL_ADDRESS_ID
JOIN [dbo].[SOURCE] ON 